### ISSUE TITLE
3. - 5 - POI on the map

### ISSUE THREAD

**Issue by ar11tehau** [Bazajee/StepOut#7]
As a user, I want to see point of interest near me

EJS Templates

Action if POI unlocked
- First thrid of the sreen
. slide mouvement
. arrow up
. title
. partial description
. sample image
. Handle the hide, when click on map option

- Whole screen
. slide mouvement
. arrow down
. title
. specific description
. image

Action if POI locked

    zoom on POI ICON
    pop up (Title, small image)

**Comment by Bazajee** [comment]
Done

**Comment by Bazajee** [comment]
Done
